[book]
authors = ["Labyte"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Labyte Book"


[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
level = 1

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.plantuml]
plantuml-cmd="java -jar /opt/plantuml.jar"

[output.html]
mathjax-support = true
additional-css = ["theme/css/style1.css","theme/css/table.css","assets/mermaid.css", "assets/print.css", "assets/all-page.css"]
additional-js = ["assets/custom3.js","assets/fzf.umd.js", "assets/elasticlunr.js", "assets/mermaid.min.js", "assets/import-html.js"]
git-repository-url = "https://github.com/labyte/book"
git-repository-icon = "fa-github"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[rust]
edition = "2021"